Build Css Style
GSG-CF04/ToDoList_04 pull request #8
Opened 2021-11-10 15:28 UTC by MohammedDahalan

relates 07

2021-11-10 16:01 UTC, abedshamia approved these changes

2021-11-10 17:21 UTC, yaqootturman requested changes

2021-11-10 17:21 UTC, yaqootturman commented on style.css
> +  header {
use class and Id selector is better than using tags name as you did

2021-11-10 17:21 UTC, yaqootturman commented on style.css
> +    padding: 10px;
Does this good if you change the width?
using pixels is not so good option too

2021-11-11 05:28 UTC, samahjamie approved these changes

2021-11-11 07:53 UTC, Yousef-Dall approved these changes

2021-11-11 07:57 UTC, yaqootturman approved these changes

2021-11-11 07:59 UTC, merged